[workspace]
resolver = "2"
members = ["crates/idiomatic-core", "crates/idiomatic-cli", "crates/idiomatic-py", "crates/idiomatic-node"]

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"
repository = "https://github.com/joeblackwaslike/idiomatic"

[workspace.dependencies]
ast-grep-config = "0.43"
ast-grep-core = "0.43"
ast-grep-language = "0.43"
serde = { version = "1", features = ["derive"] }
serde_yaml_ng = "0.10"
thiserror = "2"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
dirs = "5"
insta = { version = "1", features = ["yaml"] }
assert_cmd = "2"
serde_json = "1"
pyo3 = { version = "0.28", features = ["abi3-py39"] }
napi = { version = "3", default-features = false, features = ["napi4"] }
napi-derive = "3"
napi-build = "2"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
