/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Autofix `source` for `language`; return the fixed text and fix count. */
export declare function autofix(source: string, language: string): AutofixResult

/** Result of an autofix pass. */
export interface AutofixResult {
  fixed: string
  count: number
}

/** A single idiom match: the idiom `id` and the byte range `[start, end)`. */
export interface Hit {
  id: string
  start: number
  end: number
}

/** Lint `source` for `language`; return the list of idiom matches. */
export declare function lint(source: string, language: string): Array<Hit>

/** Render the teaching skill (SKILL.md text) for `language`. */
export declare function renderSkill(language: string): string
