[package]
name = "idiomatic-cli"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "idiomatic"
path = "src/main.rs"

[dependencies]
idiomatic-core = { path = "../idiomatic-core" }
clap.workspace = true
anyhow.workspace = true
dirs.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
